name: 用户中心
identification: notadd/member
description: 'Notadd 用户管理模块'
author:
    - Notadd
    - notadd@ibenchu.com
version: 1.0.0
assets:
    administration:
        notadd/member:
            permissions: ''
            scripts:
                - assets/member/administration/js/module.min.js
            stylesheets:
                - assets/member/administration/css/module.min.css
csrf:
    - 'api/member*'
events:
    subscribes:
        - Notadd\Member\Listeners\RouteRegister
installer: Notadd\Member\Installer
migrations:
    - databases/migrations
publishes:
    assets/member/administration: resources/mixes/administration/dist/assets/member/administration
